<?php
/**
 * Unit tests covering htaccess generation
 * @package calmPress
 * @since 1.0.0
 */

class WP_Test_Htaccess extends WP_UnitTestCase {

	/**
	 * Test mod_rewrite_rules
	 */
	public function test_mod_rewrite_rules() {
		global $wp_rewrite;

		// Make sure the htaccess generated by default is the same as the one
		// distributed.
		$generated = $wp_rewrite->mod_rewrite_rules();

		// Convert to array of lines like the one returned by extract_from_markers.
		$generated = explode( "\n", $generated );

		$file = ABSPATH . '/.htaccess';
		$default = extract_from_markers( $file, 'WordPress');
		$this->assertEquals( $default, $generated );
	}
}
