<?php
/**
 * Unit tests covering the Comment_Syntax_Help_Item_Collection class.
 *
 * @package calmPress
 * @since 1.0.0
 */

declare(strict_types=1);

use calmpress\comments\Comment_Syntax_Help_Item_Collection;
use calmpress\comments\Comment_Syntax_Help_Item_Collection_Mutator;
use calmpress\comments\Comment_Syntax_Help_Item;
use calmpress\observer\Observer;
use calmpress\observer\Observer_Priority;

/**
 * A class to mock mutator that add items at the top
 */
class Mock_Mutator_Add_Items_At_Top implements Comment_Syntax_Help_Item_Collection_Mutator {
	public function mutate_by_ref( Comment_Syntax_Help_Item_Collection &$collection ): void {
		$collection->add_items_at_top(
			new Comment_Syntax_Help_Item( 'a', 'b', 'c' ),
			new Comment_Syntax_Help_Item( 'c', 'b', 'c' ),
			new Comment_Syntax_Help_Item( 'b', 'b', 'c' ),
		);
	}

	public function notification_dependency_with( Observer $observer ): Observer_Priority	{
		return Observer_Priority::NONE;
	}
}

/**
 * A class to mock mutator that add items at the bottom
 */
class Mock_Mutator_Add_Items_At_Bottom implements Comment_Syntax_Help_Item_Collection_Mutator {
	public function mutate_by_ref( Comment_Syntax_Help_Item_Collection &$collection ): void {
		$collection->add_items_at_top(
			new Comment_Syntax_Help_Item( 'a', 'b', 'c' ),
		);
		$collection->add_items_at_bottom(
			new Comment_Syntax_Help_Item( 'ba', 'b', 'c' ),
			new Comment_Syntax_Help_Item( 'bc', 'b', 'c' ),
			new Comment_Syntax_Help_Item( 'bb', 'b', 'c' ),
		);
	}

	public function notification_dependency_with( Observer $observer ): Observer_Priority	{
		return Observer_Priority::NONE;
	}
}

/**
 * A class to mock mutator that tests remove_items
 */
class Mock_Mutator_Remove_Items implements Comment_Syntax_Help_Item_Collection_Mutator {
	public function mutate_by_ref( Comment_Syntax_Help_Item_Collection &$collection ): void {
		$collection->add_items_at_bottom(
			new Comment_Syntax_Help_Item( 'ba', 'b', 'c' ),
			new Comment_Syntax_Help_Item( 'bc', 'b', 'c' ),
			new Comment_Syntax_Help_Item( 'bb', 'b', 'c' ),
		);
		$collection->remove_items( 'not here', 'bc', 'bb' );
		$collection->add_items_at_top(
			new Comment_Syntax_Help_Item( 'bb', 'b', 'c' ),
		);
	}

	public function notification_dependency_with( Observer $observer ): Observer_Priority	{
		return Observer_Priority::NONE;
	}
}

/**
 * A class to mock mutator that add items at mixed top and bottom order.
 */
class Mock_Mutator_Add_Mixed implements Comment_Syntax_Help_Item_Collection_Mutator {
	public function mutate_by_ref( Comment_Syntax_Help_Item_Collection &$collection ): void {
		$collection->add_items_at_top(
			new Comment_Syntax_Help_Item( 'a', 'b', 'c' ),
		);
		$collection->add_items_at_bottom(
			new Comment_Syntax_Help_Item( 'aa', 'b', 'c' ),
		);
		$collection->add_items_at_top(
			new Comment_Syntax_Help_Item( 'aaa', 'b', 'c' ),
		);
		$collection->add_items_at_bottom(
			new Comment_Syntax_Help_Item( 'aaaa', 'b', 'c' ),
		);
	}

	public function notification_dependency_with( Observer $observer ): Observer_Priority	{
		return Observer_Priority::NONE;
	}
}

class Comment_Syntax_Help_Item_Collection_Test extends WP_UnitTestCase {

	/**
	 * test all_items on empty collection.
	 * 
	 * @since 1.0.0
	 */
	public function test_empty_all_items() {
		$o = new Comment_Syntax_Help_Item_Collection();
		$ar = iterator_to_array( $o->all_items() );
		$this->assertTrue( empty( $ar ) );
	}

	public function test_constructor_same_ids() {

		$thrown = false;
		try {
			$o = new Comment_Syntax_Help_Item_Collection(
				new Comment_Syntax_Help_Item( 'a', 'b', 'c' ),
				new Comment_Syntax_Help_Item( 'b', 'b', 'c' ),
				new Comment_Syntax_Help_Item( 'a', 'ba', 'ca' ),
			);
		} catch ( Exception $e ) {
			$thrown = true;
		}
		$this->assertTrue( $thrown );
	}

	/**
	 * Test the add_items_at_top
	 *
	 * @since 1.0.0
	 */
	public function test_add_items_at_top() {

		// Adding after onstruction fnished throws.
		$thrown = false;
		try {
			$o = new Comment_Syntax_Help_Item_Collection();
			$o->add_items_at_top( new Comment_Syntax_Help_Item( 'a', 'b', 'c' ) );
		} catch ( Exception $e ) {
			$thrown = true;
		}
		$this->assertTrue( $thrown );

		// Add element on top with a mutator.
		$m = new Mock_Mutator_Add_Items_At_Top();
		Comment_Syntax_Help_Item_Collection::register_mutator( $m );
	
		$o = new Comment_Syntax_Help_Item_Collection();

		// Check order of elements generated by all_items and that there only 3.
		$ar = iterator_to_array( $o->all_items() );
		$this->assertSame( 3, count( $ar ) );
		$this->assertSame( 'a', $ar[0]->id );
		$this->assertSame( 'c', $ar[1]->id );
		$this->assertSame( 'b', $ar[2]->id );

		// test with some initial item
		$o = new Comment_Syntax_Help_Item_Collection(
			new Comment_Syntax_Help_Item( 'first', 'b', 'c' )
		);
		$ar = iterator_to_array( $o->all_items() );
		$this->assertSame( 4, count( $ar ) );
		$this->assertSame( 'a', $ar[0]->id );
		$this->assertSame( 'c', $ar[1]->id );
		$this->assertSame( 'b', $ar[2]->id );
		$this->assertSame( 'first', $ar[3]->id );

		Comment_Syntax_Help_Item_Collection::remove_observer( $m );


	}

	/**
	 * Test the add_items_at_bottom
	 *
	 * @since 1.0.0
	 */
	public function test_add_items_at_bottom() {

		// Adding after onstruction fnished throws.
		$thrown = false;
		try {
			$o = new Comment_Syntax_Help_Item_Collection();
			$o->add_items_at_bottom( new Comment_Syntax_Help_Item( 'a', 'b', 'c' ) );
		} catch ( Exception $e ) {
			$thrown = true;
		}
		$this->assertTrue( $thrown );

		// Add elements a mutator.
		$m = new Mock_Mutator_Add_Items_At_Bottom();
		Comment_Syntax_Help_Item_Collection::register_mutator( $m );
		$o = new Comment_Syntax_Help_Item_Collection();

		// Check order of elements generated by all_items and that there only 3.
		$ar = iterator_to_array( $o->all_items() );
		$this->assertSame( 4, count( $ar ) );
		$this->assertSame( 'a', $ar[0]->id );
		$this->assertSame( 'ba', $ar[1]->id );
		$this->assertSame( 'bc', $ar[2]->id );
		$this->assertSame( 'bb', $ar[3]->id );

		// test with some initial item
		$o = new Comment_Syntax_Help_Item_Collection(
			new Comment_Syntax_Help_Item( 'first', 'b', 'c' )
		);
		$ar = iterator_to_array( $o->all_items() );
		$this->assertSame( 5, count( $ar ) );
		$this->assertSame( 'a', $ar[0]->id );
		$this->assertSame( 'first', $ar[1]->id );
		$this->assertSame( 'ba', $ar[2]->id );
		$this->assertSame( 'bc', $ar[3]->id );
		$this->assertSame( 'bb', $ar[4]->id );

		Comment_Syntax_Help_Item_Collection::remove_observer( $m );
	}

	/**
	 * Test the item addition at API at mixed order
	 *
	 * @since 1.0.0
	 */
	public function test_add_items_mixed() {

		// Add elements a mutator.
		$m = new Mock_Mutator_Add_Mixed();
		Comment_Syntax_Help_Item_Collection::register_mutator( $m );
		$o = new Comment_Syntax_Help_Item_Collection();

		// Check order of elements generated by all_items and that there only 3.
		$ar = iterator_to_array( $o->all_items() );
		$this->assertSame( 4, count( $ar ) );
		$this->assertSame( 'aaa', $ar[0]->id );
		$this->assertSame( 'a', $ar[1]->id );
		$this->assertSame( 'aa', $ar[2]->id );
		$this->assertSame( 'aaaa', $ar[3]->id );

		// test with some initial item
		$o = new Comment_Syntax_Help_Item_Collection(
			new Comment_Syntax_Help_Item( 'first', 'b', 'c' )
		);
		$ar = iterator_to_array( $o->all_items() );
		$this->assertSame( 5, count( $ar ) );
		$this->assertSame( 'aaa', $ar[0]->id );
		$this->assertSame( 'a', $ar[1]->id );
		$this->assertSame( 'first', $ar[2]->id );
		$this->assertSame( 'aa', $ar[3]->id );
		$this->assertSame( 'aaaa', $ar[4]->id );

		Comment_Syntax_Help_Item_Collection::remove_observer( $m );
	}

	/**
	 * Test the remove_items
	 *
	 * @since 1.0.0
	 */
	public function test_remove_items() {

		// Adding after onstruction fnished throws.
		$thrown = false;
		try {
			$o = new Comment_Syntax_Help_Item_Collection();
			$o->remove_items( 'a' );
		} catch ( Exception $e ) {
			$thrown = true;
		}
		$this->assertTrue( $thrown );

		$m = new Mock_Mutator_Remove_Items();
		Comment_Syntax_Help_Item_Collection::register_mutator( $m );
		$o = new Comment_Syntax_Help_Item_Collection();

		// Check order of elements generated by all_items and that there only 3.
		$ar = iterator_to_array( $o->all_items() );
		$this->assertSame( 2, count( $ar ) );
		$this->assertSame( 'bb', $ar[0]->id );
		$this->assertSame( 'ba', $ar[1]->id );

		Comment_Syntax_Help_Item_Collection::remove_observer( $m );
	}

	/**
	 * Test id_exists
	 * 
	 * @since 1.0.0
	 */
	public function test_id_exists() {
		$m = new Mock_Mutator_Remove_Items();
		Comment_Syntax_Help_Item_Collection::register_mutator( $m );
		$o = new Comment_Syntax_Help_Item_Collection();

		// Check order of elements generated by all_items and that there only 3.
		$this->assertTrue( $o->id_exists( 'bb' ) );
		$this->assertFalse( $o->id_exists( 'not here' ) );
		$this->assertFalse( $o->id_exists( 'bc' ) );

		Comment_Syntax_Help_Item_Collection::remove_observer( $m );
	}
}